### ISSUE TITLE
Please consider changing license from GPL-3.0-only to GPL-3.0-or-later

### ISSUE THREAD

**Issue by rl2939** [scanner-darkly/eightfold#1]
## The Problem:
Eightfold is (at the time this bug report is written) licensed under the GPL-3.0-only licencse. This is a problem because this license prevents Eightfold from being included in other open source projects such as [Cardinal](https://github.com/DISTRHO/Cardinal), which [can't accept modules made with this license](https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include).

## Suggested Solution:
Change the license of Eightfold to GPL-3.0-or-later (also known as GPLv3.0+).

## See also (other module developers):
- https://github.com/sebastien-bouffier/Bidoo/issues/186

**Comment by scanner-darkly** [comment]
i'm okay with changing it to GPLv3.0+ but i'm not sure how to actually do it, github doesn't seem to provide it as an option, and i can't find the wording for it.

**Comment by dromer** [comment]
@scanner-darkly you simply have to change your `plugin.json` to say `GPL-3.0-or-later` -> https://github.com/scanner-darkly/eightfold/blob/main/plugin.json#L5

It's an explicit clause in the GPL that you activate by mentioning it in your documentation etc.
(ideally your code has this at the top somewhere. Just the SPDX identifier is enough)

**Comment by scanner-darkly** [comment]
done! https://github.com/scanner-darkly/eightfold/commit/a541c5cfdc3fb9ad8e4f345470f817eaf576b987
